#! /bin/bash
# display the average block processing time
# Usage: avetimes [recent]
# where [recent] is an optional number specifying how many recent blocks to average

# check if optional parameter is present
if [[ $1 == "" ]]
then
    times=`grep "Time" blocks/*.txt | sed 's@blocks/\([0-9][0-9]*\)\.txt:Time: \([0-9][0-9]*\).*@\1 \2@' | sort -n | cut -d' ' -f 2`
else
    times=`grep "Time" blocks/*.txt | sed 's@blocks/\([0-9][0-9]*\)\.txt:Time: \([0-9][0-9]*\).*@\1 \2@' | sort -n | cut -d' ' -f 2 | tail -$1`
fi

# process each time ignoring any out of range
sum=0
items=0
skipped=0
for time in $times
do
    if [[ $time -ge 400 && $time -lt 900 ]]
    then
        items=$((items+1))
        sum=$((sum+$time))
    else
        skipped=$((skipped+1))
    fi
done

# calculate the average
average=$((sum/$items))
echo $average

# if any were skipped display how many
if [[ $skipped -gt 0 ]]
then
    echo "Skipped $skipped out of $items"
fi
